build-app:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
  script:
    - echo "🐳 Building Docker Compose stack..."
    - echo "DATABASE_URL=${DATABASE_URL}" > build.env
    - docker compose --env-file build.env -f docker-compose.yml build
    - docker image ls
    - docker save fintech512-project_ledgervest-web -o app.tar
  artifacts:
    paths:
      - app.tar
    expire_in: 1 hour
  only:
    - main
